# Deployment Service
apiVersion: v1
kind: Service
metadata:
  name: deploy
  labels:
    project: little-project
    owner: daisuke
spec:
  selector:
    project: little-project
    app: deployment-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: daemon
spec:
  selector:
    project: little-project
    app: daemonset-app
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
